import React from 'react';
import {
  Document,
  Page,
  Text,
  View,
  StyleSheet,
} from '@react-pdf/renderer';
import { renderToBuffer } from '@react-pdf/renderer';
import { selectTemplate, renderTemplate, buildTemplateVars } from './templates';
import type { YCSAFEVariant } from './templates';

const styles = StyleSheet.create({
  page: {
    padding: 60,
    fontFamily: 'Helvetica',
    fontSize: 10,
    lineHeight: 1.6,
    color: '#1a1a2e',
  },
  header: {
    textAlign: 'center',
    marginBottom: 30,
    borderBottomWidth: 2,
    borderBottomColor: '#7c3aed',
    paddingBottom: 20,
  },
  headerTitle: {
    fontSize: 20,
    fontFamily: 'Helvetica-Bold',
    color: '#7c3aed',
    marginBottom: 4,
  },
  headerSubtitle: {
    fontSize: 12,
    color: '#6b7280',
    fontFamily: 'Helvetica',
  },
  partiesSection: {
    marginBottom: 24,
    padding: 16,
    backgroundColor: '#f5f3ff',
    borderRadius: 4,
  },
  partiesTitle: {
    fontSize: 13,
    fontFamily: 'Helvetica-Bold',
    color: '#4c1d95',
    marginBottom: 10,
  },
  partyRow: {
    flexDirection: 'row',
    marginBottom: 6,
  },
  partyLabel: {
    width: 100,
    fontFamily: 'Helvetica-Bold',
    fontSize: 10,
    color: '#374151',
  },
  partyValue: {
    flex: 1,
    fontSize: 10,
    color: '#1f2937',
  },
  termsSection: {
    marginBottom: 24,
  },
  termsTitle: {
    fontSize: 13,
    fontFamily: 'Helvetica-Bold',
    color: '#4c1d95',
    marginBottom: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#e5e7eb',
    paddingBottom: 6,
  },
  termRow: {
    flexDirection: 'row',
    marginBottom: 4,
    paddingVertical: 3,
  },
  termLabel: {
    width: 160,
    fontFamily: 'Helvetica-Bold',
    fontSize: 10,
    color: '#374151',
  },
  termValue: {
    flex: 1,
    fontSize: 10,
    color: '#1f2937',
  },
  bodyText: {
    fontSize: 10,
    lineHeight: 1.6,
    color: '#374151',
    marginBottom: 12,
    textAlign: 'justify',
  },
  sectionTitle: {
    fontSize: 11,
    fontFamily: 'Helvetica-Bold',
    color: '#1f2937',
    marginTop: 16,
    marginBottom: 8,
  },
  signatureSection: {
    marginTop: 40,
    borderTopWidth: 1,
    borderTopColor: '#e5e7eb',
    paddingTop: 20,
  },
  signatureTitle: {
    fontSize: 13,
    fontFamily: 'Helvetica-Bold',
    color: '#4c1d95',
    marginBottom: 20,
  },
  signatureBlock: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  signatureColumn: {
    width: '45%',
  },
  signatureLabel: {
    fontSize: 10,
    fontFamily: 'Helvetica-Bold',
    color: '#374151',
    marginBottom: 6,
  },
  signatureLine: {
    borderBottomWidth: 1,
    borderBottomColor: '#9ca3af',
    marginBottom: 4,
    height: 30,
  },
  signatureSubtext: {
    fontSize: 8,
    color: '#6b7280',
    marginBottom: 2,
  },
  footer: {
    position: 'absolute',
    bottom: 30,
    left: 60,
    right: 60,
    flexDirection: 'row',
    justifyContent: 'space-between',
    borderTopWidth: 1,
    borderTopColor: '#e5e7eb',
    paddingTop: 8,
  },
  footerText: {
    fontSize: 8,
    color: '#9ca3af',
  },
});

export interface SAFEDocumentData {
  companyName: string;
  founderName: string;
  founderTitle: string;
  investorName: string;
  investorTitle: string;
  investmentAmount: string;
  valuationCap: string;
  discountRate: string;
  vestingMonths: number;
  cliffMonths: number;
  state: string;
  date: string;
  template: string;
  proRata: boolean;
  mfnClause: boolean;
}

const VARIANT_LABELS: Record<YCSAFEVariant, string> = {
  'valuation-cap': 'Post-Money Valuation Cap',
  'discount': 'Post-Money Discount',
  'mfn': 'Most Favored Nation',
};

export function SAFEDocument({ data }: { data: SAFEDocumentData }) {
  const { variant, template: tmpl } = selectTemplate({
    valuation_cap: parseFloat(data.valuationCap.replace(/[^0-9.]/g, '')) || 0,
    discount: parseFloat(data.discountRate) || 0,
  });

  const rendered = renderTemplate(tmpl, {
    company_name: data.companyName,
    investor_name: data.investorName,
    investor_title: data.investorTitle,
    founder_name: data.founderName,
    founder_title: data.founderTitle,
    investment_amount: data.investmentAmount,
    valuation_cap: data.valuationCap,
    discount_rate: data.discountRate,
    state: data.state,
    date: data.date,
  });

  const paragraphs = rendered
    .split('\n\n')
    .map((p) => p.trim())
    .filter(Boolean);

  return (
    <Document>
      <Page size="LETTER" style={styles.page}>
        <View style={styles.header}>
          <Text style={styles.headerTitle}>
            SAFE (Simple Agreement for Future Equity)
          </Text>
          <Text style={styles.headerSubtitle}>
            {VARIANT_LABELS[variant]} — Generated by Givvy
          </Text>
        </View>

        <View style={styles.partiesSection}>
          <Text style={styles.partiesTitle}>Parties</Text>
          <View style={styles.partyRow}>
            <Text style={styles.partyLabel}>Company:</Text>
            <Text style={styles.partyValue}>{data.companyName}</Text>
          </View>
          <View style={styles.partyRow}>
            <Text style={styles.partyLabel}>Founder:</Text>
            <Text style={styles.partyValue}>
              {data.founderName} — {data.founderTitle}
            </Text>
          </View>
          <View style={styles.partyRow}>
            <Text style={styles.partyLabel}>Investor:</Text>
            <Text style={styles.partyValue}>
              {data.investorName} — {data.investorTitle}
            </Text>
          </View>
          <View style={styles.partyRow}>
            <Text style={styles.partyLabel}>Date:</Text>
            <Text style={styles.partyValue}>{data.date}</Text>
          </View>
        </View>

        <View style={styles.termsSection}>
          <Text style={styles.termsTitle}>Key Terms</Text>
          <View style={styles.termRow}>
            <Text style={styles.termLabel}>SAFE Type:</Text>
            <Text style={styles.termValue}>{VARIANT_LABELS[variant]}</Text>
          </View>
          <View style={styles.termRow}>
            <Text style={styles.termLabel}>Investment Amount:</Text>
            <Text style={styles.termValue}>{data.investmentAmount}</Text>
          </View>
          {variant === 'valuation-cap' && (
            <View style={styles.termRow}>
              <Text style={styles.termLabel}>Post-Money Valuation Cap:</Text>
              <Text style={styles.termValue}>{data.valuationCap}</Text>
            </View>
          )}
          {variant === 'discount' && (
            <View style={styles.termRow}>
              <Text style={styles.termLabel}>Discount Rate:</Text>
              <Text style={styles.termValue}>{data.discountRate}%</Text>
            </View>
          )}
          <View style={styles.termRow}>
            <Text style={styles.termLabel}>Vesting:</Text>
            <Text style={styles.termValue}>
              {data.vestingMonths} months with {data.cliffMonths}-month cliff
            </Text>
          </View>
          <View style={styles.termRow}>
            <Text style={styles.termLabel}>Governing Law:</Text>
            <Text style={styles.termValue}>State of {data.state}</Text>
          </View>
        </View>

        <View>
          <Text style={styles.termsTitle}>Full Agreement</Text>
          {paragraphs.map((paragraph, index) => {
            const isHeading =
              paragraph === paragraph.toUpperCase() &&
              paragraph.length < 80;
            return isHeading ? (
              <Text key={index} style={styles.sectionTitle}>
                {paragraph}
              </Text>
            ) : (
              <Text key={index} style={styles.bodyText}>
                {paragraph}
              </Text>
            );
          })}
        </View>

        <View style={styles.signatureSection}>
          <Text style={styles.signatureTitle}>Signatures</Text>
          <View style={styles.signatureBlock}>
            <View style={styles.signatureColumn}>
              <Text style={styles.signatureLabel}>
                COMPANY: {data.companyName}
              </Text>
              <View style={styles.signatureLine} />
              <Text style={styles.signatureSubtext}>
                {data.founderName}
              </Text>
              <Text style={styles.signatureSubtext}>
                {data.founderTitle}
              </Text>
              <Text style={styles.signatureSubtext}>Date: ____________</Text>
            </View>
            <View style={styles.signatureColumn}>
              <Text style={styles.signatureLabel}>
                INVESTOR: {data.investorName}
              </Text>
              <View style={styles.signatureLine} />
              <Text style={styles.signatureSubtext}>
                {data.investorName}
              </Text>
              <Text style={styles.signatureSubtext}>
                {data.investorTitle}
              </Text>
              <Text style={styles.signatureSubtext}>Date: ____________</Text>
            </View>
          </View>
        </View>

        <View style={styles.footer} fixed>
          <Text style={styles.footerText}>
            Givvy — Confidential
          </Text>
          <Text
            style={styles.footerText}
            render={({ pageNumber, totalPages }) =>
              `Page ${pageNumber} of ${totalPages}`
            }
          />
        </View>
      </Page>
    </Document>
  );
}

export async function generateSAFEPDF(
  data: SAFEDocumentData
): Promise<Buffer> {
  const buffer = await renderToBuffer(
    <SAFEDocument data={data} />
  );
  return Buffer.from(buffer);
}

/**
 * Build SAFEDocumentData from deal + startup + talent records.
 * Used by the auto-generation flow and PDF download endpoint.
 */
export function buildSAFEDocData(
  deal: any,
  startup: any,
  talent: any
): SAFEDocumentData {
  const vars = buildTemplateVars(deal, startup, talent);
  return {
    companyName: vars.company_name,
    founderName: vars.founder_name,
    founderTitle: vars.founder_title,
    investorName: vars.investor_name,
    investorTitle: vars.investor_title,
    investmentAmount: vars.investment_amount,
    valuationCap: vars.valuation_cap,
    discountRate: vars.discount_rate,
    vestingMonths: deal.safe_terms?.vesting_schedule ?? deal.vesting_months ?? 48,
    cliffMonths: deal.safe_terms?.cliff_period ?? deal.cliff_months ?? 12,
    state: vars.state,
    date: vars.date,
    template: deal.safe_terms?.template ?? 'yc-standard',
    proRata: deal.safe_terms?.pro_rata ?? false,
    mfnClause: deal.safe_terms?.mfn_clause ?? false,
  };
}
